//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Proyecto.Gastos.Repository.Data
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class Tarjetas
    {
        [Key]
        public short id { get; set; }
        public string nombre { get; set; }
        public Nullable<double> monto { get; set; }
        public Nullable<System.DateTime> fechaCierre { get; set; }
        public Nullable<System.DateTime> fechaVenc { get; set; }
        public Nullable<int> numTarjeta { get; set; }
    }
}
